{% set name = "ipython-autotime" %}
{% set version = "0.1" %}
{% set sha256 = "4570af779adfa2ea256dedc743e3ba2d12740c67e9b71e080283c12abc83b9c7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - ipython

test:
  imports:
  - autotime

about:
  home: https://github.com/cpcloud/ipython-autotime
  license: MIT
  license_family: MIT
  # license_file: LICENSE # When added to MANIFEST.in – https://github.com/cpcloud/ipython-autotime/pull/6
  summary: 'Time everything in IPython'
  dev_url: https://github.com/cpcloud/ipython-autotime

extra:
  recipe-maintainers:
    - proinsias
