travis:
  secure:
    BINSTAR_TOKEN: NSNV8mjU+ftxtbzaufVrgkqeNTMv+NEb0wTL7PlOFHkgpafDtCPhrNPJKe95ZrrnhvZ2oRan80KKrAjJF5Op7hZLosKz4xYxgFAw2ENwmv/sUPAE8kaJ64OLfPqI6RD/Egd3neausbIYuajdqoCgBCiRkmse+E9HG2w1xPDuDpKUI1vfujjnjXiNfV7Go6JbkVYMWvdXG/p/7JO0mbZrlqfzUpXF11C+u82/r7zN9Ga4hImFiV2cTuw7hOKbH58R6MUjr7IgweQzN3tpqf0B9eDo8uKRmMYhwy8bi+etbf9pBXBI/wi3JfhWFfXH7GK6iWuWxVuE4zHtmDanm/FyVYTM4LipQE99t5yNUp+P0brlsxf1Wx1Cg6ksWAIgoyh1FMnOd2ygh0ugVWpXDmNy/o162olRYTUUreqfnKMAafhia22NTaluFOj4MOoLsHUMPIZoQve412ljc/C8sDerH6YFVb3zFPQV6gwgCisjwGlDHGVHRX55+uspeSpuXnku8Z6yN4Xzmqv2VfFxModlMTgUU5Xrwq6JLMnfi4UeVQhTeVLkyLLWsyEG8SpPqW8RnryfodfyGB7UTM9e+eA+WBfTBhMKw0N4JJprUSmqwrZtYwvh4iuqTUP5GGmUR5l3A4kYFV5t8W9JA5SJlnMeAoe/FBMgvST/iK2pCIILiyE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
